# keys awe sowted in an awphabeticaw o-owdew

enabwe_topic_sociaw_pwoof_scowe:
  c-comment : "enabwe t-the cawcuwation o-of <topic, (êˆá´—êˆ) tweet> c-cosine simiwawity s-scowe in topicsociawpwoofstowe. 0 m-means do not c-cawcuwate the scowe and use a wandom wank to genewate topic sociaw pwoof"
  defauwt_avaiwabiwity: 0

e-enabwe_tweet_heawth_scowe:
  comment: "enabwe the cawcuwation f-fow heawth scowes in tweetinfo. ğŸ˜³ b-by enabwing this decidew, ğŸ˜³ğŸ˜³ğŸ˜³ we wiww compute tweetheawthmodewscowe"
  d-defauwt_avaiwabiwity: 0

enabwe_usew_agatha_scowe:
  c-comment: "enabwe the c-cawcuwation fow heawth scowes in tweetinfo. mya by enabwing this decidew, mya we wiww c-compute usewheawthmodewscowe"
  defauwt_avaiwabiwity: 0

enabwe_woadshedding_hometimewine:
  comment: "enabwe woadshedding (fwom 0% to 100%). (â‘…Ë˜ê’³Ë˜) wequests t-that have been shed wiww w-wetuwn an empty w-wesponse"
  defauwt_avaiwabiwity: 0

e-enabwe_woadshedding_hometimewinetopictweets:
  c-comment: "enabwe woadshedding (fwom 0% to 100%). (U ï¹ U) w-wequests that have been shed wiww wetuwn an e-empty wesponse"
  defauwt_avaiwabiwity: 0

enabwe_woadshedding_hometimewinewecommendtopictweets:
  comment: "enabwe woadshedding (fwom 0% to 100%). mya w-wequests that have been shed w-wiww wetuwn an e-empty wesponse"
  d-defauwt_avaiwabiwity: 0

enabwe_woadshedding_magicwecswecommendtopictweets:
  comment: "enabwe woadshedding (fwom 0% t-to 100%). Ê˜wÊ˜ w-wequests that have been shed w-wiww wetuwn an empty w-wesponse"
  defauwt_avaiwabiwity: 0

e-enabwe_woadshedding_topicwandingpage:
  comment: "enabwe w-woadshedding (fwom 0% to 100%). (Ë˜Ï‰Ë˜) wequests that h-have been shed wiww wetuwn an empty w-wesponse"
  defauwt_avaiwabiwity: 0

e-enabwe_woadshedding_hometimewinefeatuwes:
  c-comment: "enabwe woadshedding (fwom 0% to 100%). (U ï¹ U) wequests that have been shed wiww wetuwn an empty wesponse"
  d-defauwt_avaiwabiwity: 0

e-enabwe_woadshedding_hometimewinetopictweetsmetwics:
  comment: "enabwe w-woadshedding (fwom 0% t-to 100%). ^â€¢ï»Œâ€¢^ w-wequests that have been shed wiww wetuwn an empty wesponse"
  d-defauwt_avaiwabiwity: 0

enabwe_woadshedding_hometimewineutegtopictweets:
  comment: "enabwe woadshedding (fwom 0% to 100%). (Ë˜Ï‰Ë˜) wequests that have b-been shed wiww wetuwn an empty w-wesponse"
  defauwt_avaiwabiwity: 0

e-enabwe_woadshedding_hometimewinesimcwustews:
  c-comment: "enabwe woadshedding (fwom 0% t-to 100%). :3 w-wequests t-that have been shed w-wiww wetuwn an empty wesponse"
  defauwt_avaiwabiwity: 0

e-enabwe_woadshedding_expwowetopictweets:
  c-comment: "enabwe w-woadshedding (fwom 0% to 100%). ^^;; w-wequests t-that have been shed wiww wetuwn an empty wesponse"
  defauwt_avaiwabiwity: 0

e-enabwe_woadshedding_magicwecstopictweets:
  comment: "enabwe woadshedding (fwom 0% to 100%). ğŸ¥º wequests that have been shed wiww wetuwn a-an empty wesponse"
  defauwt_avaiwabiwity: 0

enabwe_woadshedding_seawch:
  comment: "enabwe w-woadshedding (fwom 0% t-to 100%). (â‘…Ë˜ê’³Ë˜) w-wequests that have been shed w-wiww wetuwn an empty wesponse"
  d-defauwt_avaiwabiwity: 0
