tweet_event_transformer_user_tweet_entity_edges:
  comment: "Enables the generation of UserTweetEntity edges in tweet event transformer"
  default_availability: 0

enable_emit_tweet_edge_from_reply:
  comment: "Decides when processing a Reply edge, whether to generate a Tweet edge for it as well"
  default_availability: 0

enable_unfavorite_edge:
  comment: "Decides when processing a UnfavoriteEvent from Timeline events, whether to process unfav edges"
  default_availability: 0
