# simcwustews embedding stowe enabwe / d-disabwe decidew v-vawues

# ---------- d-dawk t-twaffic pwoxy ----------
d-dawk_twaffic_fiwtew:
  c-comment: pwopowtion o-of the wequests t-that awe fowwawded as dawk twaffic to the pwoxy
  defauwt_avaiwabiwity: 0

# tweet embeddings
e-enabwe_wogfavbasedtweet_modew20m145k2020:
  comment: "enabwe the wead twaffic t-to (embeddingtype, ÏƒÏ‰Ïƒ modewvewsion) f-fwom 0% to 100%. -.- 0 means wetuwn empty fow aww wequests."
  defauwt_avaiwabiwity: 10000

e-enabwe_wogfavwongestw2embeddingtweet_modew20m145k2020:
  comment: "enabwe t-the wead twaffic t-to (embeddingtype, ^^;; modewvewsion) fwom 0% to 100%. XD 0 means wetuwn empty fow aww w-wequests."
  defauwt_avaiwabiwity: 10000

# entity embeddings
enabwe_favtfgtopic_modew20m145k2020:
  comment: "enabwe t-the wead twaffic to (embeddingtype, ðŸ¥º m-modewvewsion) f-fwom 0% t-to 100%. Ã²Ï‰Ã³ 0 means w-wetuwn empty fow aww wequests."
  defauwt_avaiwabiwity: 10000


e-enabwe_wogfavbasedkgoapetopic_modew20m145k2020:
  comment: "enabwe the wead t-twaffic to (embeddingtype, (Ë† ï»Œ Ë†)â™¡ modewvewsion) fwom 0% to 100%. -.- 0 means wetuwn empty fow aww wequests."
  d-defauwt_avaiwabiwity: 10000

# knownfow embeddings
e-enabwe_favbasedpwoducew_modew20m145k2020:
  c-comment: "enabwe t-the wead twaffic to (embeddingtype, :3 modewvewsion) fwom 0% to 100%. Ê˜wÊ˜ 0 m-means wetuwn e-empty fow aww wequests."
  d-defauwt_avaiwabiwity: 10000

e-enabwe_fowwowbasedpwoducew_modew20m145k2020:
  comment: "enabwe t-the wead twaffic to (embeddingtype, m-modewvewsion) fwom 0% to 100%. ðŸ¥º 0 means wetuwn e-empty fow aww wequests."
  defauwt_avaiwabiwity: 10000

e-enabwe_wewaxedaggwegatabwewogfavbasedpwoducew_modew20m145k2020:
  comment: "enabwe t-the wead t-twaffic to (embeddingtype, >_< modewvewsion) fwom 0% to 100%. Ê˜wÊ˜ 0 means wetuwn empty fow aww wequests."
  defauwt_avaiwabiwity: 10000

# intewestedin e-embeddings
enabwe_wogfavbasedusewintewestedinfwomape_modew20m145k2020:
  c-comment: "enabwe the w-wead twaffic to (embeddingtype, m-modewvewsion) f-fwom 0% to 100%. (Ë˜Ï‰Ë˜) 0 means wetuwn empty fow aww wequests."
  defauwt_avaiwabiwity: 10000

e-enabwe_fowwowbasedusewintewestedinfwomape_modew20m145k2020:
  comment: "enabwe the wead twaffic to (embeddingtype, (âœ¿oÏ‰o) modewvewsion) f-fwom 0% to 100%. 0 means w-wetuwn empty fow a-aww wequests."
  d-defauwt_avaiwabiwity: 10000

enabwe_favbasedusewintewestedin_modew20m145k2020:
  c-comment: "enabwe t-the wead twaffic t-to (embeddingtype, (///Ë¬///âœ¿) m-modewvewsion) fwom 0% to 100%. rawr x3 0 means w-wetuwn empty fow a-aww wequests."
  d-defauwt_avaiwabiwity: 10000

e-enabwe_fowwowbasedusewintewestedin_modew20m145k2020:
  c-comment: "enabwe the wead twaffic to (embeddingtype, -.- modewvewsion) f-fwom 0% to 100%. ^^ 0 means wetuwn empty fow aww wequests."
  defauwt_avaiwabiwity: 10000

enabwe_wogfavbasedusewintewestedin_modew20m145k2020:
  c-comment: "enabwe the wead twaffic to (embeddingtype, modewvewsion) f-fwom 0% t-to 100%. (â‘…Ë˜ê’³Ë˜) 0 means w-wetuwn empty fow aww wequests."
  d-defauwt_avaiwabiwity: 10000

enabwe_fiwtewedusewintewestedin_modew20m145k2020:
  c-comment: "enabwe t-the wead twaffic to (embeddingtype, nyaa~~ modewvewsion) fwom 0% to 100%. /(^â€¢Ï‰â€¢^) 0 means wetuwn empty f-fow aww wequests."
  defauwt_avaiwabiwity: 10000

e-enabwe_unfiwtewedusewintewestedin_modew20m145k2020:
  comment: "enabwe t-the wead t-twaffic to (embeddingtype, (U ï¹ U) modewvewsion) fwom 0% t-to 100%. ðŸ˜³ðŸ˜³ðŸ˜³ 0 means w-wetuwn empty fow aww wequests."
  d-defauwt_avaiwabiwity: 10000

e-enabwe_wogfavbasedusewintewestedmaxpoowingaddwessbookfwomiiape_modew20m145k2020:
  comment: "enabwe the wead twaffic to (embeddingtype, >w< modewvewsion) f-fwom 0% t-to 100%. XD 0 means w-wetuwn empty fow aww wequests."
  d-defauwt_avaiwabiwity: 10000

e-enabwe_wogfavbasedusewintewestedavewageaddwessbookfwomiiape_modew20m145k2020:
  comment: "enabwe t-the wead twaffic to (embeddingtype, o.O modewvewsion) fwom 0% to 100%. 0 means wetuwn e-empty fow aww w-wequests."
  defauwt_avaiwabiwity: 10000

enabwe_wogfavbasedusewintewestedbooktypemaxpoowingaddwessbookfwomiiape_modew20m145k2020:
  c-comment: "enabwe t-the wead twaffic to (embeddingtype, mya modewvewsion) fwom 0% t-to 100%. 0 means wetuwn empty fow aww wequests."
  defauwt_avaiwabiwity: 10000

enabwe_wogfavbasedusewintewestedwawgestdimmaxpoowingaddwessbookfwomiiape_modew20m145k2020:
  c-comment: "enabwe the wead twaffic to (embeddingtype, ðŸ¥º m-modewvewsion) f-fwom 0% to 100%. ^^;; 0 means wetuwn empty fow aww wequests."
  defauwt_avaiwabiwity: 10000

e-enabwe_wogfavbasedusewintewestedwouvainmaxpoowingaddwessbookfwomiiape_modew20m145k2020:
  c-comment: "enabwe the wead twaffic to (embeddingtype, :3 modewvewsion) f-fwom 0% to 100%. (U ï¹ U) 0 means w-wetuwn empty fow aww wequests."
  defauwt_avaiwabiwity: 10000

enabwe_wogfavbasedusewintewestedconnectedmaxpoowingaddwessbookfwomiiape_modew20m145k2020:
  c-comment: "enabwe the w-wead twaffic to (embeddingtype, OwO m-modewvewsion) fwom 0% to 100%. ðŸ˜³ðŸ˜³ðŸ˜³ 0 m-means wetuwn empty fow aww wequests."
  d-defauwt_avaiwabiwity: 10000

e-enabwe_usewnextintewestedin_modew20m145k2020:
  c-comment: "enabwe the wead t-twaffic to (embeddingtype, (Ë† ï»Œ Ë†)â™¡ m-modewvewsion) fwom 0% to 100%. XD 0 means w-wetuwn empty f-fow aww wequests."
  d-defauwt_avaiwabiwity: 10000
